### ISSUE TITLE
Submit to Spark

### ISSUE THREAD

**Issue by warmdog** [nielsutrecht/spark-of-life#1]
why i submit the code to spark ,get the wrong answer:
java.lang.NoClassDefFoundError: joptsimple/OptionSpec

my part of pom.xml:
 <dependency>
            <groupId>net.sf.jopt-simple</groupId>
            <artifactId>jopt-simple</artifactId>
            <version>5.0.2</version>
   </dependency>

**Comment by nielsutrecht** [comment]
You can't just submit the whole project as a .jar to spark. The project isn't set up that way; it's just an example. More info: http://spark.apache.org/docs/latest/submitting-applications.html
